# These are supported funding model platforms

github: [JerryI, KirillBelovTest] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ["https://opencollective.com/wljs-notebook", "https://www.paypal.com/donate/?hosted_button_id=BN9LWUUUJGW54"]
